### ISSUE TITLE
[BUG] Request body form parameters do not support complex composed schema use cases

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#10415]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Request body form parameters do not support complex composed schema use cases
When we handle request body form parameters here:
https://github.com/OpenAPITools/openapi-generator/blob/fdb13c3e2e5fa96523102d7c92ae2a6b409c47d4/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L6001
Our code traverses composed schemas and pools all properties inside objects into the returned properties map.
This will not work when:
- two schemas define a property with the same name and different types
- we have oneOf or anyOf schemas where some properties should be included and others shouldn't

This code path is used when request bodies are content-type application/x-www-form-urlencoded, or content-type starts with multipart

##### openapi-generator version

5.2.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  version: '1.0.0'
  title: the title

paths:
  '/users/me':
    post:
      description: Change user password.
      operationId: changeCurrentUserPassword
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Successful operation
          content: {}

components:
  schemas:
    CommonPasswordRequest:
      type: object
      required: [ password, passwordConfirmation ]
      properties:
        password:
          type: string
          format: password
        passwordConfirmation:
          type: string
          format: password

    ChangePasswordRequest:
      type: object
      allOf:
        - $ref: '#/components/schemas/CommonPasswordRequest'
        - type: object
          required: [ oldPassword ]
          properties:
            oldPassword:
              type: string
              format: password
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/10396

##### Suggest a fix

Update this code to return a single CodegenParameter which represents the composed schema in these cases.
Then the generator will require than an instance of the model that this refers to is passed in.
This fix should only be done for generators which support full composition.
For now our code only handles object schema and pure allOf with no colliding property definitions.

**Comment by sebastianblesgen** [comment]
Same issue with 5.3.1 of the plugin (java). Models are not generated when `ref$ `is used. 
I got message like _"Model XXX not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)" in my console"_

Here is my workaround but this should not be the fix as skipFormModel should be true only for OA2 as I understand. The problem I think is related to the fact it's "marked as unused (due to form parameters)"

```
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                        ...
                            <globalProperties>
                                <skipFormModel>false</skipFormModel>
                            </globalProperties>
                        </configuration>
```

**Comment by RockyMM** [comment]
Same issue with 5.4.0

**Comment by spacether** [comment]
This has been fixed in the new python-experimental generator which supports Inline schemas anywhere.

**Comment by RockyMM** [comment]
I hope Java/Spring generator has the same fix 🙏

**Comment by spacether** [comment]
Does anoyone want to submit a PR changing the default behavior for skipFormModel = false rather than true for the 6.0.0 release?
Because it is a major release, one can make breaking changes like that.

**Comment by wing328** [comment]
this has been fixed in 6.x as we've improved the inline schema handling for all generators in the default codegen.

if there's still an issue, please open a new one for tracking instead.

**Comment by ayhanap** [comment]
still happens with typescript-axios generator. inlining `requestBody` instead of using `$ref` fixes the issue.

**Comment by namitaofficial22** [comment]
Still happens for go generator

**Comment by Elmira1313** [comment]
hi, this worked in my case, just added  `globalProperty`
```
{
    "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
    "spaces": 2,
    "generator-cli": {
        "version": "6.5.0",
        "generators": {
            "v1.0": {
                "generatorName": "typescript-axios",
                "output": "./src/api/axios-client",
                "skipValidateSpec": true,
                "inputSpec": "http://localhost:9000/swagger/v1/swagger.json",
                "additionalProperties": {
                    "supportsES6": true,
                    "useSingleRequestParameter": true
                },
                "globalProperty": {
                    "skipFormModel": false
                }
            }
        }
    }
}
```
