### ISSUE TITLE
[BUG][Python] OneOf creates a pydantic Field which is not support in pydantic v2 const=True

### ISSUE THREAD

**Issue by bykof** [OpenAPITools/openapi-generator#16176]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

If I create a schema that has a oneOf or anyOf  field, it generates a pydantic Field with const=True.
The keyword const=True is deprecated and removed in pydantic v2.
The error is: `PydanticUserError('constis removed, useLiteral instead'`

##### openapi-generator version

v6.6.0

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
```

##### Generation Details

docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -g python --additional-properties=generateSourceCodeOnly=true,packageName=client --skip-validate-spec -o /local/ -i /local/openapi.yaml

##### Suggest a fix

Change to `Literal` instead of using `Field(..., const=True)`

**Comment by fa0311** [comment]
This issue has been fixed.
#15189

**Comment by lvijnck** [comment]
@fa0311 @wing328 how to use this version? I am using the latest version of the CLI, i.e., latest.

**Comment by lvijnck** [comment]
@fa0311 The produced code still contains `Field(..., const=True)` as opposed to `Literal`. I have updated my dependencies.

**Comment by fa0311** [comment]
@lvijnck
> The produced code still contains `Field(..., const=True)` as opposed to `Literal`.

Yes. The generated code contains `Field(..., const=True)`
PydanticUserError error can be avoided by setting the pydantic v2.

**Comment by lvijnck** [comment]
@fa0311 Error is still there for me.

Using:

```
pydantic==2.2.1
```

And the following code to produce my source code:

```
docker run --rm \
    -v "${PWD}:/src" openapitools/openapi-generator-cli:latest generate \
    -i /src/asset-service/openapi/core-api.json \
    -g python \
    -o /src/asset-service/src \
    --additional-properties=generateSourceCodeOnly=true,packageName=core_api,library=asyncio
```

Happy to share my specs as needed. For now, I just removed the following line from the generated source code and committed it to my repo, which feels like a mess.

```
one_of_schemas: List[str] = Field(.., const=True)
```

Why is this field added anyway? It does not seem to be used?

Thanks for the response!

**Comment by fa0311** [comment]
@lvijnck 
> PydanticUserError error can be avoided by setting the pydantic v2.
> 
> The current openapi-generator Python generator does not support pydantic v3

This was my typo, actually v2 was a mistake for v1 and v3 was a mistake for v2.


> Or do you mean it does not work with Pydantic v2?

Exactly, use v1 as v2 is not supported.

**Comment by lvijnck** [comment]
I just bumped my entire API to Python 3.11 so I'd rather not go back. I will have some capacity end of month to contribute back to the generators. So will be in touch. Thanks!

**Comment by lvijnck** [comment]
Why is this closed?
