### ISSUE TITLE
[BUG] Unable to generate shared external reference DTOs for open API 3.1

### ISSUE THREAD

**Issue by pkernevez** [OpenAPITools/openapi-generator#18361]
##### Description
I try to move from openapi 3.0.3 to 3.1, but I have a strange behaviour with ref schema.
With 3.0.3 ref schemas are generated (java/spring) with a dedicated Dto, example a schema common.Amount creates  a Dto CommonAmount that use as is from all the places.
With 3.1 it now creates a new schema for all the places it’s used.
It’s not related to the generator, but to the parsing: It changed in file OpenAPIV3Parser, L211 `if (result.getOpenAPI().getOpenapi() != null && result.getOpenAPI().getOpenapi().startsWith("3.1")) { `

I had a maven/springboot project to reproduce it: https://github.com/pkernevez/pb-openapi
The only difference in swaggers “3.0” and “3.1" are the version in the first line.
In my example, I have a share type : common.Amount (a quantity and a currency).
With 3.0.3 I have a shared type CommonAmount, with 3.1 I now have a new type for each usage (here market value).
Why this behaviour changed ?
Is there a way to restore the previous way ?

Having a new class for each usage is an issue to define only once shared code, like mapping Entity <-> Dto

![image](https://github.com/OpenAPITools/openapi-generator/assets/338699/2fdd2766-badf-416e-aff4-f4e7f5112587)

##### openapi-generator version
Tested with :
* 7.4.0
* 7.5.0-SNAPSHOT on April 11th.

##### OpenAPI declaration file content or url

* v3.0.3 version
https://github.com/pkernevez/pb-openapi/blob/master/src/main/resources/swagger/accounting-swagger-v3-0.yaml
* v3.1.0 version:
https://github.com/pkernevez/pb-openapi/blob/master/src/main/resources/swagger/accounting-swagger-v3-1.yaml

##### Generation Details

APIs are the same, the issues is for Dtos.

<img width="458" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/338699/b6d9a469-b687-4850-9873-ce01d70749cb">

##### Steps to reproduce

```
mvn clean install
find target/generated-sources/src/main/java/net/kernevez/generated
```

**Comment by pkernevez** [comment]
Additionally and probably related to this:
On top of it, I have a share ErrorDto type. Before (3.0.3) it was uses as is : CommonError for the different Error declarations, but now it creates a new type for the first usage, meaning my error 400 and 404 are returning a type named GetPosition400Response

**Comment by wing328** [comment]
did you have a chance to try the latest master? we've merged a couple of fixes related to 3.1 spec

https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.5.0-SNAPSHOT/

**Comment by pkernevez** [comment]
Yes,
as mentioned in my ticket, I tested it with 7.4.0 & 7.5.0-SNAPSHOT on April 11th.
I recheck now with 7.5.0-20240412.172223 and I have the same behavior.

**Comment by wing328** [comment]
i'm able to repeat the issue:
```diff
-openapi: 3.0.3
+openapi: 3.1.0
 info:
   title: An example
   version: "1.0"
@@ -12,11 +12,15 @@ paths:
     get:
       operationId: getPosition
       parameters:
-      - in: query
+      - explode: true
+        in: query
         name: accountId
         required: true
         schema:
-          $ref: '#/components/schemas/common.Tsid'
+          example: 0FHP0N1QTKMBS
+          format: b32
+          type: string
+        style: form
       - example: 2024-01-05
         explode: true
         in: query
@@ -37,118 +41,89 @@ paths:
           content:
             application/json:
               schema:
-                $ref: '#/components/schemas/common.ErrorDto'
+                description: Generic container for errors
+                example:
+                  errorCode: ErrorCode
+                  errorMessage: Error message
+                  errorDetails: Error details
+                  correlationId: 08d3b3e0-a300-4fac-9837-dd8c2fd1e899
+                properties:
+                  errorCode:
+                    type: string
+                  errorMessage:
+                    type: string
+                  errorDetails:
+                    type: string
+                  correlationId:
+                    type: string
           description: Invalid request data
         "404":
           content:
             application/json:
               schema:
-                $ref: '#/components/schemas/common.ErrorDto'
+                description: Generic container for errors
+                example:
+                  errorCode: ErrorCode
+                  errorMessage: Error message
+                  errorDetails: Error details
+                  correlationId: 08d3b3e0-a300-4fac-9837-dd8c2fd1e899
+                properties:
+                  errorCode:
+                    type: string
+                  errorMessage:
+                    type: string
+                  errorDetails:
+                    type: string
+                  correlationId:
+                    type: string
```

I suspect it's swagger parser issue for 3.1 spec (even though I use `setResolveFully(false)` when debugging this issue) as you can it seems to force `setResolveFully` to true for 3.1 spec (but not 3.0.x spec).

can you please open an issue in the swagger parser repo when you've time?

**Comment by yweigang** [comment]
I´m having the same Issue when upgrading from openapi 3.0.3 to 3.1.0 
It still exists with openapi-generator 7.11.0

**Comment by pkernevez** [comment]
Any new on this ticket ?
I have the same issue with the 3.0.3 version by using openapi-plugin version 7.11.0
It's a breaking change

**Comment by pkernevez** [comment]
This is not related to the parser it's a change in the generator. The only difference between 7.10 and 7.11 in term of dependence is a small version change in org.yaml:snakeyaml

<img width="1568" alt="Image" src="https://github.com/user-attachments/assets/761fd3d1-99a4-4ee5-ad97-48d9d7fa4e5a" />

**Comment by wing328** [comment]
just merged https://github.com/OpenAPITools/openapi-generator/pull/21293 to update snakepyaml to latest stable version

can you please pull the latest master to give it a try?

link to snapshot version (published in ~30 mins via CI) can be found in project's readme

**Comment by wing328** [comment]
did anyone have a minute to do a test?

snapshot versions in https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.14.0-SNAPSHOT/

**Comment by noshua** [comment]
@wing328 I'm suffering from this issue using 7.14.0 stable.

**Comment by wing328** [comment]
@noshua thanks for doing another test to confirm it's still an issue.

filed https://github.com/OpenAPITools/openapi-generator/pull/21512 to revert the version back to 2.2

can you please test it?

https://github.com/OpenAPITools/openapi-generator/pull/21512

```
git clone --depth 1 https://github.com/openAPITools/openapi-generator -b snakeyaml-revert
cd openapi-generator
./mvnw clean package -DskipTests
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i /path/to/your/spec.yaml -o /tmp/java-okhttp/
```

(repalce ./mvnw with mvnw.cmd if you're using Windows)

**Comment by wing328** [comment]
@pkernevez did you have a chance to update to the latest stable version? is the issue resolved?

**Comment by noshua** [comment]
@wing328 I tried the snakeyaml-revert branch but it still generates wrong classnames like `AddAuditLogRequestNewInner.java` instead of just `AuditLogRequest.java`.

**Comment by wing328** [comment]
@noshua if you spec rolls back to 3.0 (instead of 3.1), do you still encounter the same issue?

from what I tell, looks like the issue you reported is different than the one opened here

to have complete control of inner schema naming, please refer to https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#inline-schema-naming

**Comment by wing328** [comment]
One may want to use swagger-cli to resolve the references as a workaround:

https://github.com/OpenAPITools/openapi-generator/issues/11151#issuecomment-997276841

**Comment by noshua** [comment]
> [@noshua](https://github.com/noshua) if you spec rolls back to 3.0 (instead of 3.1), do you still encounter the same issue?
> 
> from what I tell, looks like the issue you reported is different than the one opened here
> 
> to have complete control of inner schema naming, please refer to https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#inline-schema-naming

With 3.0 everything works fine. There should be no inner class... only a AuditLogRequest.java from the AuditLogRequest.yaml. Look at the difference using the same yaml-Files:

**3.0**
<img width="289" height="284" alt="Image" src="https://github.com/user-attachments/assets/fb124066-6f6a-4cd9-b5a1-3f73915c38d6" />

**3.1**
<img width="341" height="184" alt="Image" src="https://github.com/user-attachments/assets/94262e74-fdf1-4d77-a388-e2696928bc8d" />

**Comment by rockinrimmer** [comment]
This issue looks similar to the issue I just raised https://github.com/OpenAPITools/openapi-generator/issues/21535

**Comment by Kavan72** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/22753
