### ISSUE TITLE
[BUG] [Kotlin] Optional parameters

### ISSUE THREAD

**Issue by dlazerka** [OpenAPITools/openapi-generator#2012]
#### Bug Report Checklist

- [+] Have you provided a full/minimal spec to reproduce the issue?
- [+] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [+] What's the version of OpenAPI Generator used?
- [+] Have you search for related issues/PRs?
- [+] What's the actual output vs expected output?
Generated argument types are `kotlin.String`, but should be `kotlin.String?`

##### Description

Client code generated: It is impossible to _not_ provide an optional param to an API.

##### openapi-generator version
4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
  version: "2.1.4"
  title: "Test"
  description: ""
host: "example.cm"
basePath: "/2_0"
schemes:
  - "https"
paths:
  /data/foo:
    get:
      operationId: "getFoo"
      produces:
        - "application/json"
      parameters:
        - name: "t0"
          in: "query"
          required: false
          type: "string"
          format: "date-time"
          description: "Filter by start time, e.g. '2018-03-01T00-00'"
      responses:
        200:
          description: "200 response"
          schema:
            type: "string"
```
##### Command line used for generation
`java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i test.yaml -g kotlin -o tmp/kotlin/
`
##### Steps to reproduce

1. Generate the code.
1. Open vi tmp/kotlin/src/main/kotlin/org/openapitools/client/apis/DefaultApi.kt
1. See `getFoo` argument type. 

##### Suggest a fix

Arguments for which spec says "required: false", should be optional (followed by `?` in Kotlin).

**Comment by karismann** [comment]
this issue can be closed as it has been fixed by the related PR with 4.0.0

**Comment by isycat** [comment]
Heads up, the issue has not been fixed:
1. Omitting the "= null" from "paramName: TypeName? = null" in method signatures forces the consumer to specify null as the value, which makes the "required: false" parameter effectively required, albeit nullable.

2. The implementation _does not_ handle nullable header values 
`val localVariableHeaders: MutableMap<String, String> = mutableMapOf("headerName" to headerName.toString(),`... see [petstore](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/kotlin-string/src/main/kotlin/org/openapitools/client/apis/PetApi.kt#L91)
This passes the string "null" downstream.

#2 is pretty major, as it renders the implementation unusable for APIs that don't handle the "null" header value, e.g. A pretty standard implementation of kotlin-spring, where the value of 'optionalParam' in `@RequestHeader(value="optionalHeader", required=false) optionalHeader: String?,` comes through as the string "null"

**Comment by isycat** [comment]
I have submitted a small PR re. the above:
https://github.com/OpenAPITools/openapi-generator/pull/7341

Who should I @? Someone/everyone from the kotlin technical committee? Or is posting here enough?

**Comment by grEvenX** [comment]
@wing328 This issue can probably be closed?

**Comment by ablil** [comment]
Im using version 7.1.0 and this issues is still there, generated params are not optional (nullable)
