### ISSUE TITLE
[BUG] Breaking change in v7.17.0: missing RestApplication class

### ISSUE THREAD

**Issue by chromey** [OpenAPITools/openapi-generator#22543]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

v7.17.0 includes #22169 which "disable[s] generating RootResource and RootApplication if generating interfaces, since these files make no sense in the context of generating interface". However I would argue that they do, because while I am using `interfaceOnly` and providing my own API implementations, those could still take advantage of the `@ApplicationPath` annotation on the `RestApplication` class to provide a common base path for the `@Path` annotations on the interfaces. In fact, when this feature was originally introduced in [#13377](https://github.com/OpenAPITools/openapi-generator/pull/13377), a similar setup was explicitly discussed.

In v7.17.0 when using `interfaceOnly`, the context path is no longer prepended to resources (or even available for programmatic access), causing 404 errors.

##### openapi-generator version

v7.17.0

##### Steps to reproduce

1. Use jaxrs-spec generator with `interfaceOnly=true`
2. Generate code with v7.17.0
3. Try to use generated interfaces in RESTEasy Quarkus application
4. Observe 404 errors for endpoints

##### Related issues/PRs

- #22279 addresses a similar regression caused by the same change, but this is its own thing

##### Suggest a fix

Either bring back `RestApplication` and `RestResourceRoot`, or provide an option to prepend the context path to the interfaces' `@Path` annotation.

**Comment by wing328** [comment]
thanks for the feedback.

cc @rignicat who is the author of #22169

**Comment by rignicat** [comment]
I think was reported in https://github.com/OpenAPITools/openapi-generator/issues/22279 and fixed in https://github.com/OpenAPITools/openapi-generator/pull/22316 

Can you check and close if this is correct? or let me know if it isn't @chromey

**Comment by rupert-jung-mw** [comment]
Not sure if this is related but after updating 7.17.0 -> 7.18.0 my base path of URLs is also ignored for all REST calls against generated APIs, resulting in 404s for all calls. Might be a regression of this fix.

See https://github.com/OpenAPITools/openapi-generator/issues/22631

After reverting back to 7.17.0 it worked again.

**Comment by chromey** [comment]
> I think was reported in https://github.com/OpenAPITools/openapi-generator/issues/22279 and fixed in https://github.com/OpenAPITools/openapi-generator/pull/22316

Sorry for the late response @rignicat . No I think this is a separate issue. In fact 7.16, 7.17 and now 7.18 behave consistently for me in terms of `@Path` annotations on interfaces, and the issue introduced in 7.17 is not fixed in 7.18. Let me give you some more context to clarify:

For this OpenAPI spec:

```yaml
openapi: 3.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /persons:
    get:
      operationId: getPersons
  /persons/{id}:
    get:
      operationId: getPersonById
```

all three versions generate the same path annotations on the interface:

```java
@Path("/persons")
public interface PersonsApi {

    @GET
    @Path("/{id}")
    Response getPersonById(@PathParam("id") UUID id);

    @GET
    Response getPersons();
}
```

What is different is that 7.16 also generated the following:

```java
public class RestResourceRoot {
    public static final String APPLICATION_PATH = "/api";
}

@ApplicationPath(RestResourceRoot.APPLICATION_PATH)
public class RestApplication extends Application {

}
```

So now the Person resource is available at `http://localhost:8080/persons` rather than `http://localhost:8080/api/persons`

**Comment by chromey** [comment]
@rignicat @wing328 could you perhaps reconsider my last response? As far as I can tell this is still not fixed in 7.23. Thanks a lot

**Comment by wing328** [comment]
> servers:
>  - url: http://localhost:8080/api

why not remove `api` from the server url instead?

**Comment by chromey** [comment]
Because the correct base path is in fact /api. The options I do have is either prepending /api before every path in the spec, or manually defining a base path in the app outside of generated artifacts. Maybe this is the intention, but it is still a breaking change that was never communicated as such.

Edit: Plus, now having re-read my initial issue ;) I would argue that the current solution introduced an inconsistency in how it handles base paths depending on the value of `interfaceOnly` that, to me, seems hard to justify.

**Comment by wing328** [comment]
>  "disable[s] generating RootResource and RootApplication if generating interfaces, since these files make no sense in the context of generating interface"

is that still a correct statement when generating interfaces?

**Comment by chromey** [comment]
Was that a question for me? The statement isn't mine, and my asssessment of it immediately followed:

>  However I would argue that they do, because while I am using interfaceOnly and providing my own API implementations, those could still take advantage of the @ApplicationPath annotation on the RestApplication class to provide a common base path for the @Path annotations on the interfaces.

**Comment by rignicat** [comment]
I've superficially followed this today, I'll take a look when I have time @chromey - I'll post a followup within a week

**Comment by rignicat** [comment]
I did not forget about this, I do obviously need a bit more time. sorry!

**Comment by rignicat** [comment]
@chromey sorry it took a while - I created a PR which should resolve this, by decoupling interfaceOnly and generating the root resources (as you suggested!)

there is now a new config item, `generateRootResources` (default enabled) which will generate root resources if interfaceOnly is true. this should restore default behaviour to pre-7.17.0

Please test it and let me know if this resolves your issue!

**Comment by chromey** [comment]
Thanks @rignicat , sounds great! Will test it asap.

**Comment by wing328** [comment]
Just merged the PR by @rignicat 

Please give it a try with the latest master.

Closing the issue for now
