### ISSUE TITLE
typescript-node generates invalid typescript

### ISSUE THREAD

**Issue by kpturner** [OpenAPITools/openapi-generator#2384]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Using a valid swagger JSON I generated a client using the following command:
```
openapi-generator  generate -i the.json -l typescript-node
```
The resulting code is invalid Typescript and cannot be transpiled without manual intervention:

```
import Promise = require('bluebird');
```
The above line is completely redundant in Typescript.  There is no requirement to use bluebird as promises are part of the basic node offering.

```
import { ObjectSerializer, Authentication, HttpBasicAuth, ApiKeyAuth, OAuth, VoidAuth } from '../model/models';
```
error TS6133: 'HttpBasicAuth' is declared but its value is never read.
error TS6133: 'ApiKeyAuth' is declared but its value is never read.
error TS6133: 'OAuth' is declared but its value is never read.

Apart from the errors themselves, it is concerning that no oauth authentication is included in the `authentications` property.

Asynchronous methods (those that return a Promise) should be declared as `async` methods.  For example, this:
```
public calculateLine (calculateLineRequest: CalculateLineRequest) : Promise<{ response: http.ClientResponse; body: CalculateLineResponse;  }>
```
should be
```
public async calculateLine (calculateLineRequest: CalculateLineRequest) : Promise<{ response: http.ClientResponse; body: CalculateLineResponse;  }>
```
otherwise typescript consumers of the API cannot use `await` when calling the API method.

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

I cannot provide this as it a private commercial API 

##### Command line used for generation

```
openapi-generator  generate -i the.json -l typescript-node
```

##### Steps to reproduce
Just generate the code

##### Suggest a fix

Drop the reference to bluebird.
Declare asynchronous methods as `async`
Investigate why there is no oauth authentication

**Comment by macjohnny** [comment]
sounds good. would you like to give it a try and fix it?

**Comment by kpturner** [comment]
I am not sure I have the capacity to investigate it and fix it. At the moment we are just manually (programmatically) fixing up the generated code.

**Comment by kpturner** [comment]
I have given it a try in a locally cloned repo that I branched off master.  However I don't know how you would prefer me to proceed with regard to a PR?   Firstly is it `master` that you want me to branch from or not?  I cannot `push` anything upstream because I am not authorised so do I need to be a contributor?    

My change was simply to `typescript-nodeapi-single.mustache`:

```
{{>licenseInfo}}
import localVarRequest = require('request');
import http = require('http');

/* tslint:disable:no-unused-locals */
{{#imports}}
import { {{classname}} } from '../{{filename}}';
{{/imports}}

import { ObjectSerializer, Authentication, VoidAuth } from '../model/models';
{{#hasAuthMethods}}
{{#authMethods}}
{{#isBasic}}
import { HttpBasicAuth } from '../model/models';
{{/isBasic}}
{{#isApiKey}}
import { OApiKeyAuth } from '../model/models';
{{/isApiKey}}
{{#isOAuth}}
import { OAuth } from '../model/models';
{{/isOAuth}}
{{/authMethods}}
{{/hasAuthMethods}}

let defaultBasePath = '{{{basePath}}}';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

{{#operations}}
{{#description}}
/**
* {{&description}}
*/
{{/description}}
export enum {{classname}}ApiKeys {
{{#authMethods}}
{{#isApiKey}}
    {{name}},
{{/isApiKey}}
{{/authMethods}}
}

export class {{classname}} {
    protected _basePath = defaultBasePath;
    protected defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
{{#hasAuthMethods}}
{{#authMethods}}
{{#isBasic}}
        '{{name}}': new HttpBasicAuth(),
{{/isBasic}}
{{#isApiKey}}
        '{{name}}': new ApiKeyAuth({{#isKeyInHeader}}'header'{{/isKeyInHeader}}{{^isKeyInHeader}}'query'{{/isKeyInHeader}}, '{{keyParamName}}'),
{{/isApiKey}}
{{#isOAuth}}
        '{{name}}': new OAuth(),
{{/isOAuth}}
{{/authMethods}}
{{/hasAuthMethods}}
    }

    constructor(basePath?: string);
{{#authMethods}}
{{#isBasic}}
    constructor(username: string, password: string, basePath?: string);
{{/isBasic}}
{{/authMethods}}
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
{{#authMethods}}
{{#isBasic}}
            this.username = basePathOrUsername;
            this.password = password
{{/isBasic}}
{{/authMethods}}
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: {{classname}}ApiKeys, value: string) {
        (this.authentications as any)[{{classname}}ApiKeys[key]].apiKey = value;
    }
{{#hasAuthMethods}}
{{#authMethods}}
{{#isBasic}}
    set username(username: string) {
        this.authentications.{{name}}.username = username;
    }

    set password(password: string) {
        this.authentications.{{name}}.password = password;
    }
{{/isBasic}}
{{#isOAuth}}

    set accessToken(token: string) {
        this.authentications.{{name}}.accessToken = token;
    }
{{/isOAuth}}
{{/authMethods}}
{{/hasAuthMethods}}

{{#operation}}
    /**
     * {{&notes}}
     {{#summary}}
     * @summary {{&summary}}
     {{/summary}}
     {{#allParams}}
     * @param {{paramName}} {{description}}
     {{/allParams}}
     */
    public async {{nickname}} ({{#allParams}}{{paramName}}{{^required}}?{{/required}}: {{{dataType}}}, {{/allParams}}options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.{{#supportsES6}}IncomingMessage{{/supportsES6}}{{^supportsES6}}ClientResponse{{/supportsES6}}; {{#returnType}}body: {{{returnType}}}; {{/returnType}}{{^returnType}}body?: any; {{/returnType}} }> {
        const localVarPath = this.basePath + '{{{path}}}'{{#pathParams}}
            .replace('{' + '{{baseName}}' + '}', encodeURIComponent(String({{paramName}}))){{/pathParams}};
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
        let localVarFormParams: any = {};

{{#allParams}}
{{#required}}
        // verify required parameter '{{paramName}}' is not null or undefined
        if ({{paramName}} === null || {{paramName}} === undefined) {
            throw new Error('Required parameter {{paramName}} was null or undefined when calling {{nickname}}.');
        }

{{/required}}
{{/allParams}}
{{#queryParams}}
        if ({{paramName}} !== undefined) {
            localVarQueryParameters['{{baseName}}'] = ObjectSerializer.serialize({{paramName}}, "{{{dataType}}}");
        }

{{/queryParams}}
{{#headerParams}}
        localVarHeaderParams['{{baseName}}'] = ObjectSerializer.serialize({{paramName}}, "{{{dataType}}}");
{{/headerParams}}
        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

{{#formParams}}
        if ({{paramName}} !== undefined) {
            {{#isFile}}
            localVarFormParams['{{baseName}}'] = {{paramName}};
            {{/isFile}}
            {{^isFile}}
            localVarFormParams['{{baseName}}'] = ObjectSerializer.serialize({{paramName}}, "{{{dataType}}}");
            {{/isFile}}
        }
{{#isFile}}
        localVarUseFormData = true;
{{/isFile}}

{{/formParams}}
        let localVarRequestOptions: localVarRequest.Options = {
            method: '{{httpMethod}}',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
{{^isResponseFile}}
            json: true,
{{/isResponseFile}}
{{#isResponseFile}}
            encoding: null,
{{/isResponseFile}}
{{#bodyParam}}
            body: ObjectSerializer.serialize({{paramName}}, "{{{dataType}}}")
{{/bodyParam}}
        };

{{#authMethods}}
        this.authentications.{{name}}.applyToRequest(localVarRequestOptions);

{{/authMethods}}
        this.authentications.default.applyToRequest(localVarRequestOptions);

        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: http.{{#supportsES6}}IncomingMessage{{/supportsES6}}{{^supportsES6}}ClientResponse{{/supportsES6}}; {{#returnType}}body: {{{returnType}}}; {{/returnType}}{{^returnType}}body?: any; {{/returnType}} }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    {{#returnType}}
                    body = ObjectSerializer.deserialize(body, "{{{returnType}}}");
                    {{/returnType}}
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    }
{{/operation}}
}
{{/operations}}
```

**Comment by macjohnny** [comment]
please fork the repository, create a new branch from master and file a PR against master. I will be happy to review your changes

**Comment by kpturner** [comment]
OK

**Comment by wing328** [comment]
@kpturner this may help: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements

**Comment by kpturner** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/2452

**Comment by adam-ah** [comment]
I'm not sure this is the correct place to raise, but there is another problem too:
```
error TS2694: Namespace '"http"' has no exported member 'ClientResponse'.
```
The code looks like this:
```
public remoteMethod (param: String....) : Promise<{ response: http.ClientResponse; body: Response;  }> {
```

It appears that ClientResponse has been removed since Node 10 (I'm on 11.7.0), using the same version of generator (3.3.4).

A related bug:
https://github.com/OpenAPITools/openapi-generator/issues/1138

**Comment by wing328** [comment]
> EDIT: It appears the " --additional-properties supportsES6=true" flag will generate Node 11 compatible code. Should it be the default perhaps?

Good idea. We can make `supportsES6` the default in 4.0.0 release. May I know if you've time to file a PR for this?

**Comment by adam-ah** [comment]
I'm sorry @wing328, even though I suspect it's a one-line change, it's very unlikely I would have any time to work on this before July.

**Comment by macjohnny** [comment]
resolved in #2452

**Comment by lucaspiller** [comment]
> > EDIT: It appears the " --additional-properties supportsES6=true" flag will generate Node 11 compatible code. Should it be the default perhaps?
> 
> Good idea. We can make `supportsES6` the default in 4.0.0 release. May I know if you've time to file a PR for this?

Just in case anyone comes across this, in version 4.1.1 you still need this flag to produce output compatible with Node v10.

**Comment by jaydeep987** [comment]
I think it has other issue then ?
I am using `4.1.1` and ended up with this:

```
import { ApiKeyAuth } from '../model/models';
import { ApiKeyAuth } from '../model/models';
```
(two times lol)

any idea?

**Comment by macjohnny** [comment]
@jaydeep987 can you open a separate issue?

**Comment by dsudzy** [comment]
Im still experiencing this issue with typescript-node  `Namespace '"http"' has no exported member 'ClientResponse'. return new Promise<{ response: http.ClientResponse; body: string;  }>((resolve, reject).`  I am using version generator version 4.2.3. was the fix #2452 added to this release?

**Comment by ftatzky** [comment]
@dsudzy as @adam-ah already mentioned, you just have to add `--additional-properties supportsES6=true` to your generator command.
