### ISSUE TITLE
JaxRS Server still use Swagger v2 as dependency

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#27]
Generated JaxRS Server uses this library as dependency:

```
    <dependency>
      <groupId>io.swagger</groupId>
      <artifactId>swagger-jersey2-jaxrs</artifactId>
      <version>1.5.15</version>
    </dependency>
```

It should be:

```
    <dependency>
      <groupId>io.swagger.core.v3</groupId>
      <artifactId>swagger-jaxrs2</artifactId>
      <version>2.0.1</version>
    </dependency>
```

Of course the templates need to be changed in order to adopt the new notation and annotations...

---

The most visible impact is on the capability for the server to self describe itself.

When you run `mvn clean package jetty:run` inside the [`samples/server/petstore/jaxrs/jersey2/`](https://github.com/openapitools/openapi-generator/tree/master/samples/server/petstore/jaxrs/jersey2)  folder and then call `http://localhost:8080/v2/swagger.yaml`, you obtain the corresponding spec:

```
swagger: "2.0"
info:
  ...
host: "petstore.swagger.io:80"
basePath: "/v2"
tags:
...
schemes:
- "http"
paths:
  /another-fake/dummy:
    patch:
      ...
  /fake/outer/boolean:
    post:
      tags:
      - "fake"
      summary: ""
      description: "Test serialization of outer boolean types"
      operationId: "fakeOuterBooleanSerialize"
      consumes:
      - "*/*"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "body"
        description: "Input boolean as post body"
        required: false
        schema:
          type: "boolean"
      responses:
        200:
          description: "Output boolean"
          schema:
            type: "boolean"
  /fake/outer/composite:
    post:
      ...
  /fake/outer/number:
    ...
```

The big next step for the JaxRS generators will be to generate code that will be using Swagger v3 artefacts. Then the page to call to get the spec will be `http://localhost:8080/v2/openapi.yaml`

**Comment by jmini** [comment]
Input @wing328:

> I think that's a breaking change because users using the auto-generated code before will find the app not working after the big dependency change with the new auto-generated code.

I will try to propose something for `4.0.0-SNAPSHOT`

**Comment by mohanaraosv** [comment]
So then it doesn't support **OpenAPI 3.0.0** or is it fixed in any other PR.

**Comment by jmini** [comment]
@mohanaraosv: 
OpenAPI generator supports OpenAPI v3 (you can use this as input file). Some code generators (like the jaxrs server generator in this case) produce code that rely on Swagger v2 libraries…

As explained in this issue, it is just a matter of fixing the generator.

**Comment by dummyalias** [comment]
I have tried updating the version for the `jaxrs-*` generators, but gave up halfway, because the task became to overwhelming for me. You can see my efforts in the last commits of this branch: https://github.com/dummyalias/openapi-generator/tree/feature/swagger2_jaxrs . The changes are still untested and the following is still missing (as far as I can tell):
- More adaptations for `@ApiParam` (e.g. extracting `@DefaultValue`)
- Fixing all imports (ideally even avoid wildcards)
- Fix `pom.xml`, gradle config, ...

Maybe someone with more experience can use my efforts when fixing this issue.

**Comment by nikosmoum** [comment]
Any updates on this?
