### ISSUE TITLE
[Python] Client code is wrong when an endpoint accepts multiple MediaTypes

### ISSUE THREAD

**Issue by raubel** [OpenAPITools/openapi-generator#440]
##### Description

My OpenApi 3.0 specification contains an endpoint for which the response media type can be `application/octet-stream` or, if the query cannot be completed, `application/json`.
The generated Python client code builds a query with a MediaType being the concatenation of both: `application/octet-streamapplication/json`

##### openapi-generator version

3.0.3

##### OpenAPI declaration file content or url

Below is my (simplified) OpenApi specification:
```yaml
openapi: 3.0.0

servers:
- url: http://localhost/myapi

info:
  version: "1.0"
  title: My API

security:
- basicAuth: []

paths:

  /download:
    get:
      operationId: download
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        500:
          description: Error
          content:
            application/json:
              schema:
                type: string
```

##### Command line used for generation

I call the generator directly from my Java application:
```java
	CodegenConfigurator configurator = new CodegenConfigurator();
	configurator.setInputSpec("spec.yml");
	configurator.setGeneratorName("python");
	configurator.setOutputDir("out");
	new DefaultGenerator().opts(configurator.toClientOptInput()).generate();
```

##### Python test file

Running this script with the generated `openapi_client`
```python
import unittest
import openapi_client

configuration = openapi_client.Configuration()
configuration.debug = True

# create an instance of the API class
api_instance = openapi_client.DefaultApi(openapi_client.ApiClient(configuration))

class TestModels(unittest.TestCase):
    def test_download(self):
        api_instance.download()

if __name__ == '__main__':
    unittest.main()
```

results in the following output:
```
2018-07-02 15:17:38,841 DEBUG Starting new HTTP connection (1): localhost
send: 'GET /myapi HTTP/1.1\r\nHost: localhost:10080\r\nAccept-Encoding: identity\r\nContent-Type: application/json\r\nAccept: application/octet-streamapplication/json\r\nAuthorization: Basic c2VtYWRtaW46c2VtYWRtaW4=\r\nUser-Agent: OpenAPI-Generator/1.0.0/python\r\n\r\n'
reply: 'HTTP/1.1 406 Not Acceptable\r\n'
...
```

**Comment by ackintosh** [comment]
@raubel Thanks for reporting the issue!

It has fixed in latest release [v3.1.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.1.0), so please give it a try with latest version. 😉 

(Related PR: https://github.com/OpenAPITools/openapi-generator/pull/445 📝 )

**Comment by raubel** [comment]
@ackintosh, unfortunately, does not seem do be fixed in 3.1.0. I still have an Accept header being `application/octet-streamapplication/json`.

**Comment by ackintosh** [comment]
Oh... 😢 

Could you please check the generated file `default_api.py`?

(Below is part of files generated from [the simplified spec](https://github.com/OpenAPITools/openapi-generator/issues/440#issue-337780301))
```
├── openapi_client
│   ├── __init__.py
│   ├── api
│   │   ├── __init__.py
│   │   ├── default_api.py <<====
│   ├── api_client.py
│   ├── configuration.py
│   ├── models
│   │   ├── __init__.py
│   ├── rest.py
```

There should be the difference between `3.0.3` and `3.1.0` on `default_api.py` like below:

#### 3.0.3

L96
```python
        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/octet-stream''application/json'])  # noqa: E501
```

#### 3.1.0

L96
```python
        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/octet-stream', 'application/json'])  # noqa: E501
```

What about your `default_api.py`?

**Comment by raubel** [comment]
The generated code seems correct in `default_api.py`.

However, the code in `api_client.py` is suspicious:
````python
    def select_header_accept(self, accepts):
        """Returns `Accept` based on an array of accepts provided.

        :param accepts: List of headers.
        :return: Accept (e.g. application/json).
        """
        if not accepts:
            return

        accepts = [x.lower() for x in accepts]

        if 'application/json' in accepts:
            return 'application/json'
        else:
            return ', '.join(accepts)
````
It removes all media types exception `application/json`. It this correct?

That's why I still have a 406 (Not accepted) status code. 
(BTW, I'm not able to retrieve the `application/octet-streamapplication/json` (I was probably looking at the wrong log file).)

**Comment by ackintosh** [comment]
cc @taxpon @frol  @mbohlool @cbornet  @kenjones-cisco

**Comment by raubel** [comment]
Any update?

**Comment by ackintosh** [comment]
Sorry for late reply. 💦 

> It removes all media types except application/json. It this correct?

Maybe it is not good. (but currently most of the generated clients (even other language) has same issue.)

My understanding about why the API client removes all media types except `application/json` is...

[API client treats the response data as JSON](https://github.com/ackintosh/openapi-generator-1/blob/8867d2b34c6861667619359823ee1c3c45cbc963/samples/client/petstore/python/petstore_api/api_client.py#L226-L230) so API client sets `application/json` to Accept header preferentially.

#### My idea

I think [Quality values](https://developer.mozilla.org/en-US/docs/Glossary/Quality_values) will be good solution.

The following Accept header allows all media types and request that the response be returned as `application/json`.
```
Accept: application/json,application/octet-stream;q=0.9
```

The solution requires some works (template improvement), I'll file a PR if the idea gets someone's 👍 .

**Comment by jirikuncar** [comment]
There is a same problem in Go(-experimental).

```golang
// selectHeaderAccept join all accept types and return
func selectHeaderAccept(accepts []string) string {
	if len(accepts) == 0 {
		return ""
	}

	if contains(accepts, "application/json") {
		return "application/json"
	}

	return strings.Join(accepts, ",")
}
```

when using a param with `Accept: application/json; param=foo` only the `application/json` type from 300+ responses gets picked up.

```yaml
      responses:
        "200":
          description: OK
          content:
            application/json;param=foo:
              schema:
                $ref: "#/components/schemas/OK"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error400"
```

**Comment by ymilki** [comment]
@spacether  I don't believe #7427 fixes this issue as reported. #7427 fixes the python data type of the return value of responses )e.g. Is the return value a primitive type or model).

This issue addresses the format of the raw response (e.g. is the response "application/json" or "text/plain"). This format has implications in response deserialization.  @ackintosh  in #728 identifies this issue more explicitly and @rienafairefr in #2134 attempts to support this.

**Comment by ymilki** [comment]
I see #10978 explicitly passes the response content-type around which provides the framework to the client code to handle different content-types.

**Comment by spacether** [comment]
This code has been cleaned up in python-experimental:
- one can input content_type to control the serialization of transmitted request bodies to the server
- one can input a tuple of custom accept_content_types to control which response type(s) the server should send back
In this PR: https://github.com/OpenAPITools/openapi-generator/pull/8325
which I will merge today
