### ISSUE TITLE
[BUG][typescript-angular] use imported mapping in api

### ISSUE THREAD

**Issue by gritschf** [OpenAPITools/openapi-generator#5079]
Is there any way to use an imported mapping in the api.service itself?

I already have an external dependcy with my typings (`@entities`)  
And an api which uses them.  

If i generate the api client with 

`$ openapi-generator generate -i http://xxx -g typescript-angular  -c ./gen.cfg`

gen.cfg:
`{
  "importMappings": {
        "Payload":"@entities"
  }
}`

the import in the default.services.ts is `import { Payload } from '../@entities';` 
(because in the `api.service.mustache` the import is `import { {{classname}} } from '../{{filename}}';`)

but the correct path would be: `import { Payload } from '@entities';`   

is there any way to achieve this?

**Comment by Razzokk** [comment]
So, are there any news about this problem? I want to use an existing model in my service but he keeps getting the import wrong.

**Comment by adest** [comment]
Hello,

Can we requalify this question as a bug ?
We are currently using OpenAPI generator to generate both the server with 'spring' generator and the client with 'typescript-angular' generator.
But the generation is not symmetric:
The spring generator manages importMapping as expected for the response body;
But the typescript-angular seems to rely on importMapping only for model class's attributes but do not take them into account for response body.

That leads to incompatible client ans server implementation with the same spec files.

**Comment by agilob** [comment]
Looks like this is fixed for typescript node, but fix doesn't affect typescript-angular. 

https://github.com/OpenAPITools/openapi-generator/pull/3469

The fix should be moved  from `TypeScriptNodeClientCodegen` to `AbstractTypeScriptClientCodegen`

@adest would you like try fixing this?

**Comment by agilob** [comment]
well, never mind, it works fine in typescript-angular I had a tpyo in my conf.json :D


```
  "importMappings": {
    "MemberDTO": "app/shared/model/member.model"
  }
```

correctly generates

`import { MemberDTO } from 'app/shared/model/member.model';`

using

`npx @openapitools/openapi-generator-cli generate -i src/main/resources/swagger/api.yml -g typescript-angular -o src/main/webapp/app/models --global-property models -c typescript-angular.conf`

@wing328 this can be closed on 5.0.0 beta2

**Comment by rsi21** [comment]
Hi @agilob,

Sorry, i'm a bit lost with that feature, that i try to use too with typescript angular.

I first started using the version 4.1.2 and i add this kind of generation with a leading './':

`import { MemberDTO } from './app/shared/model/member.model';`

So i fix this issue with a post script.

And today i tested with 5.0.0 beta2 and beta3, and now there is no replacement at all for the import, i have this:

`import { MemberDTO } from  '../model/models';`

And i understood in an other issue that in fact the feature import-mapping is not supported at all for typescript-angular.
And i tested with typescript-node and yes it's working fine.

So how did you make it working with typescript-angular, i missed something ?

Thanks

**Comment by ratoaq2** [comment]
I'm facing the same issue with typescript-angular and trying to use Moment.js
```
					<importMappings>
						<importMapping>Moment=moment</importMapping>
					</importMappings>
```

the generated model is correct:
```
import { Moment } from 'moment';
```

but the generated service is not:
```
import { Moment } from '../model/models';
```

**Comment by rsi21** [comment]
Hi,

For information, I tested again with latest version 5.2.0 and issue is still there.
I found that for typescript-node it's working fine. It seems it has been fixed with the following MR:

[https://github.com/OpenAPITools/openapi-generator/pull/7410](url)

So as said by @adest I think it could be requalify as a bug ?

Thanks

**Comment by robbieaverill** [comment]
I've raised #13273 for the equivalent of this in typescript-fetch
